services:
  - type: web
    name: messenger-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: cd server && python server.py
    envVars:
      - key: PORT
        value: 10000
